"""Canonical complete-panel column schema.

This module is intentionally data-only. Exporters and normalizers should import
these constants instead of redefining complete-panel column contracts.
"""

COMPLETE_PANEL_SCHEMA_VERSION = "fundamental_complete_panel_v1"

IDENTITY_COLUMNS = (
    "quarter",
    "ticker",
    "symbol",
    "cik",
    "cik10",
    "security_id",
    "company_title",
    "cik_status",
    "ticker_as_of_decision_date",
    "ticker_mapping_source",
    "ticker_mapping_source_date",
    "ticker_mapping_effective_date",
    "ticker_mapping_pit_valid_flag",
    "ticker_mapping_missing_reason",
    "price_ticker_used",
    "facts_cik_used",
    "ticker_cik_mapping_confidence",
)

PRICE_AND_SOURCE_COLUMNS = (
    "decision_date_rule",
    "decision_date",
    "source_available_date",
    "financial_cutoff_date",
    "disclosure_available_date",
    "tradable_date",
    "tradable_date_alias_source",
    "entry_open",
    "entry_open_date",
    "entry_open_source",
    "expected_market_session_after_decision",
    "entry_open_gap_sessions",
    "entry_date_adjustment_reason",
    "price_adjustment_mode",
    "entry_open_price_basis",
    "return_price_basis",
    "entry_open_raw",
    "entry_open_adjusted_for_return_calc",
    "adjustment_factor",
    "price_reference_date",
    "price_reference_time",
    "price_reference_source",
    "price_reference_used_for_scoring_flag",
    "score_timing_mode",
    "execution_timing_mode",
    "execution_date",
    "execution_price",
    "execution_price_source",
    "execution_after_score_timestamp_flag",
    "non_executable_research_score_flag",
    "execution_timing_missing_reason",
    "prior_entry_open",
    "entry_qoq_pct",
    "prior_entry_qoq_pct",
    "panel_row_source",
    "source_file",
    "panel_build_id",
    "panel_build_timestamp",
    "feature_schema_version",
    "feature_schema_path",
    "source_run_root",
    "source_artifact",
    "source_artifact_sha256",
)

PRE_LLM_COLUMNS = (
    "pre_llm_candidate_flag",
    "pre_llm_rank_by_score_quarter",
    "revenue_value",
    "revenue_value_missing_reason",
    "net_income_value",
    "net_income_value_missing_reason",
    "assets_value",
    "assets_value_missing_reason",
    "operating_cash_flow_value",
    "operating_cash_flow_value_missing_reason",
    "investing_cash_flow_value",
    "investing_cash_flow_value_missing_reason",
    "financing_cash_flow_value",
    "financing_cash_flow_value_missing_reason",
    "revenue_bucket",
    "profitability_score",
    "operating_cash_flow_score",
    "fcf_proxy_score",
    "financing_dependence_score",
    "asset_efficiency_score",
    "pre_llm_fundamental_score",
    "pre_llm_fundamental_bucket",
    "pre_llm_fundamental_missing_fields",
    "missing_fields",
    "missing_inputs",
    "missing_critical_llm_fields",
    "coverage_status",
    "notes",
    "earnings_8k_accession",
    "earnings_8k_filing_date",
    "earnings_8k_primary_document",
    "earnings_exhibit_document",
    "periodic_accession",
    "periodic_form",
    "periodic_filing_date",
    "periodic_primary_document",
)

TIER_COLUMNS = (
    "tier_0_to_4_any_flag",
    "tier_1_to_4_any_flag",
    "tier_bucket",
    "tier_0_bucket",
    "tier_1_bucket",
    "tier_2_bucket",
    "tier_3_bucket",
    "tier_4_bucket",
    "tier_structure_score",
    "post_llm_tier_1_1_flag",
    "post_llm_tier_1_2_flag",
    "post_llm_tier_1_3_flag",
    "post_llm_tier_1_4_flag",
    "post_llm_tier_2_1_flag",
    "post_llm_tier_2_2_flag",
    "post_llm_tier_2_3_flag",
    "post_llm_tier_3_1_flag",
    "post_llm_tier_3_2_flag",
    "post_llm_tier_3_3_flag",
    "post_llm_tier_3_4_flag",
    "post_llm_tier_4_1_flag",
    "post_llm_tier_4_2_flag",
    "post_llm_tier_4_3_flag",
    "post_llm_sub_tier_bucket",
    "tier1_L1_llm_supported",
    "tier1_L2_causal_rerating",
    "tier1_L3_best_balanced",
    "tier1_L4_clean_high_priority",
    "tier1_L5_inflecting",
    "tier1_L6_mid_price_rerater",
    "tier1_L7_clean_non_distressed_rerater",
    "tier2_L1_llm_supported",
    "tier2_L2_causal_rerating",
    "tier2_L3_best_balanced",
    "tier3_L1_llm_supported",
    "tier3_L2_inflecting",
    "tier3_L3_persistent_positive",
    "tier3_L4_persistent_high_priority",
    "tier4_L1_llm_supported",
    "tier4_L2_causal_rerating",
    "tier4_L3_clean_high_priority",
)

HP_COLUMNS = (
    "hp_any_flag",
    "hp0_high_price_broad",
    "hp1_quality_pullback",
    "hp2_dislocation_momentum_priority",
    "hp2_dislocation_momentum_watch",
    "hp3_large_quality_theme_exception",
    "hp4_score_reacceleration_watch",
    "hp_production_extension",
    "hp_research_extension",
    "hp1_LLM_best",
    "hp2_LLM_best",
    "hp2_watch_LLM_best",
    "hp3_theme_confirmed",
    "hp4_LLM_supported",
    "hp_LLM_best",
    "hp_structure_score",
    "hp_adjusted_raw_score",
    "hp_adjusted_entry_score",
    "hp_adjusted_entry_score_bucket",
)

LLM_COLUMNS = (
    "llm_required_derived_flag",
    "llm_complete_derived_flag",
    "post_llm_candidate_derived_flag",
    "post_llm_high_priority_derived_flag",
    "post_llm_demote_derived_flag",
    "force_llm_extraction",
    "llm_status",
    "llm_status_missing_reason",
    "llm_required_for_full_buy_flag",
    "entry_score_is_provisional",
    "has_post_llm",
    "post_llm_missing_reason",
    "sample_id",
    "event_date",
    "accession",
    "exhibit_doc",
    "source_doc_type",
    "text_len",
    "text_path",
    "snippet_count",
    "quality_flags",
    "proof_alignment",
    "confidence",
    "blocking_issues",
    "in_tier1_post_llm_file",
    "in_tier2_post_llm_file",
    "in_tier3_post_llm_file",
    "in_tier4_post_llm_file",
    "in_hp1_hp4_post_llm_file",
    "post_llm_fundamental_score",
    "post_llm_fundamental_score_source",
    "post_llm_fundamental_score_missing_reason",
    "post_llm_fundamental_bucket",
    "post_llm_score_delta",
    "post_llm_any_flag",
    "post_llm_candidate_flag",
    "post_llm_high_priority_flag",
    "post_llm_demote_flag",
    "post_llm_demote_severity",
    "post_llm_demote_reason_code",
    "post_llm_demote_overrideable",
    "post_llm_demote_evidence",
    "causal_change",
    "negative_revision_risk",
    "negative_revision_risk_flag",
    "story_vs_numbers_gap_penalty",
    "narrative_delta_score",
    "narrative_delta_bucket",
    "operating_leverage_quality",
    "durability",
    "score_addition",
    "detected_driver_category",
    "detected_driver_name",
    "evidence_positive",
    "evidence_risk",
    "demote_risk_flag",
    "deteriorating_risk_flag",
    "llm_source_accessions",
    "llm_source_document_dates",
    "llm_source_available_date",
    "llm_prompt_input_hash",
    "llm_prompt_input_allowed_docs_only",
    "llm_generated_at",
    "llm_model",
    "llm_output_hash",
    "llm_cache_key",
    "source_packet_path",
    "reasoning_effort",
)

REPRICING_MOMENTUM_COLUMNS = (
    "rm_any_flag",
    "rm1_low_price_dislocation_momentum",
    "rm2_weak_acceleration",
    "rm3_mid_price_dislocation_momentum",
    "rm4_persistent_repricing_wave",
    "repricing_momentum_priority",
    "repricing_momentum_extension",
    "repricing_started",
    "repricing_confirmed",
    "positive_repricing_status",
    "market_repricing_score",
    "rm_buy_review_flag",
    "rm_risk_size_multiplier",
)

THEME_COLUMNS = (
    "primary_theme",
    "secondary_themes",
    "theme_tags",
    "theme_role",
    "theme_confidence",
    "theme_driver_type",
    "theme_momentum",
    "theme_evidence",
    "theme_source_type",
    "theme_source_date",
    "theme_source_available_date",
    "theme_evidence_accession",
    "theme_evidence_hash",
    "theme_pit_valid_flag",
    "theme_score_allowed_for_historical_scoring",
    "theme_evidence_summary",
    "theme_driver_summary",
    "theme_active",
    "theme_cohort_strength",
    "theme_leader_or_direct_beneficiary",
    "theme_score",
    "theme_tailwind_score",
    "theme_acceleration_score",
    "theme_external_confirmation_score",
    "theme_ai_data_center",
    "theme_ai_optical_networking",
    "theme_semiconductor_materials",
    "theme_compound_semiconductor",
    "theme_photonics",
    "theme_critical_materials",
    "theme_semicap_datacenter_confirmed",
    "filing_theme_growth_flag",
    "filing_theme_guidance_flag",
    "filing_theme_margin_flag",
    "filing_theme_customer_win_flag",
    "filing_theme_capacity_expansion_flag",
)

SCORING_COLUMNS = (
    "score_change",
    "prior_score_addition",
    "prior_pre_llm_fundamental_score",
    "total_structure_score",
    "llm_business_improvement_score",
    "fundamental_rerating_score",
    "risk_penalty_score",
    "base_entry_raw_score",
    "base_entry_score_0_100",
    "entry_raw_score",
    "entry_score_0_100",
    "entry_score_rank_by_quarter",
    "entry_score_0_100_bucket",
    "entry_score_label",
    "monitoring_adjustment",
    "monitoring_score_0_100",
    "final_rank_score_0_100",
    "rank_score_label",
    "monitoring_status",
    "hard_reject_reason",
    "entry_score_inputs",
    "signal_age_days",
    "signal_freshness_status",
    "decision_type",
    "blocked_reasons",
    "warning_reasons",
    "manual_override_outcome",
    "force_pm_underwriting_flag",
    "underwriting_path",
    "candidate_state",
    "dashboard_score_0_100",
    "research_priority",
)

SELECTION_COLUMNS = (
    "top15_selected",
    "selection_missing_reason",
    "top15_any_variant_selected",
    "top15_variants_selected",
    "top15_variant",
    "top15_selection_rank",
    "top15_selected_sleeve",
    "top15_selected_sleeve_rank",
    "top15_right_tail_exception_score",
    "top15_right_tail_exception_reason_codes",
    "top15_right_tail_exception_warning_codes",
    "top15_right_tail_exception_score_contributions",
    "top15_bucket",
    "top15_bucket_order",
    "top15_role",
    "top15_model",
    "top15_portfolio_treatment",
    "top15_operating_setting",
    "top15_operating_setting_validation_status",
    "top15_reason_codes",
    "top15_override_reason_codes",
    "selection_ranking_source_columns",
    "shadow_selected",
    "shadow_any_variant_selected",
    "shadow_variants_selected",
    "shadow_variant",
    "shadow_selection_rank",
    "shadow_selected_sleeve",
    "shadow_selected_sleeve_rank",
    "shadow_core_refill_source",
    "shadow_demoted_replacement_for",
    "shadow_core_deterioration_refill_shadow_flag",
    "shadow_refill_status",
    "shadow_right_tail_exception_score",
    "shadow_right_tail_exception_reason_codes",
    "shadow_right_tail_exception_warning_codes",
    "shadow_right_tail_exception_score_contributions",
    "shadow_top15_bucket",
    "shadow_top15_bucket_order",
    "shadow_top15_role",
    "shadow_top15_model",
    "shadow_portfolio_treatment",
    "shadow_demoted_core_flag",
    "shadow_demoted_core_replacement_ticker",
    "shadow_replacement_flag",
    "shadow_replacement_for_demoted_ticker",
    "shadow_replacement_delta_90d_pct",
    "shadow_high_score_deterioration_flag",
    "shadow_weak_no_theme_repricing_stack_flag",
    "shadow_core_deterioration_review_flag",
    "shadow_core_deterioration_downgrade_flag",
    "shadow_core_deterioration_strict_override_required",
    "shadow_core_deterioration_reason_codes",
)

BACKTEST_COLUMNS = (
    "future_outcome_available_flag",
    "future_outcome_missing_reason",
    "return_horizon_type",
    "return_exit_date_rule",
    "return_10d_pct",
    "return_exit_date_10d",
    "return_exit_price_10d",
    "return_20d_pct",
    "return_exit_date_20d",
    "return_exit_price_20d",
    "return_30d_pct",
    "return_exit_date_30d",
    "return_exit_price_30d",
    "return_60d_pct",
    "return_exit_date_60d",
    "return_exit_price_60d",
    "return_90d_pct",
    "return_exit_date_90d",
    "return_exit_price_90d",
    "winner_90d_30pct",
    "loser_90d_minus30pct",
    "is_partial_live_quarter",
    "eligible_for_backtest",
    "historical_source_sha256",
    "current_2026q2_source_sha256",
)

EXTENDED_SOURCE_COLUMNS = (
    "master_universe_source",
    "dealflow_source_stage",
    "scouts_json",
    "theme_acceleration_research_visibility",
    "theme_acceleration_rescan_flag",
    "akg_universe_tier",
    "macro_mode",
    "macro_spy",
    "macro_entry_action",
    "macro_position_size_multiplier",
    "extended_candidate_universe",
    "extended_research_universe",
)

LEGACY_SHADOW_RANK_COLUMNS = (
    "shadow_demoted_core_candidate_rank_x",
    "shadow_replacement_core_candidate_rank_x",
    "shadow_demoted_core_candidate_rank_y",
    "shadow_replacement_core_candidate_rank_y",
)

POPULATION_DIAGNOSTIC_COLUMNS = (
    "financial_values_source",
    "financial_values_namespace",
    "financial_values_concepts",
    "financial_values_source_file",
    "financial_values_missing_fields",
    "score_recompute_required_flag",
    "score_recompute_reason",
    "compatibility_alias_source",
    "identity_fill_source",
    "field_population_status",
)

REQUIRED_COMPLETE_PANEL_COLUMNS = (
    IDENTITY_COLUMNS
    + PRICE_AND_SOURCE_COLUMNS
    + PRE_LLM_COLUMNS
    + TIER_COLUMNS
    + HP_COLUMNS
    + LLM_COLUMNS
    + REPRICING_MOMENTUM_COLUMNS
    + THEME_COLUMNS
    + SCORING_COLUMNS
    + SELECTION_COLUMNS
    + BACKTEST_COLUMNS
    + EXTENDED_SOURCE_COLUMNS
    + LEGACY_SHADOW_RANK_COLUMNS
    + POPULATION_DIAGNOSTIC_COLUMNS
)

REQUIRED_NONBLANK_FIELDS = (
    "revenue_value",
    "net_income_value",
    "assets_value",
    "operating_cash_flow_value",
    "investing_cash_flow_value",
    "financing_cash_flow_value",
    "llm_status",
    "top15_selected",
)

LEGACY_COMPATIBILITY_FIELDS = (
    "post_llm_tier_1_1_flag",
    "post_llm_tier_1_2_flag",
    "post_llm_tier_1_3_flag",
    "post_llm_tier_1_4_flag",
    "post_llm_tier_2_1_flag",
    "post_llm_tier_2_2_flag",
    "post_llm_tier_2_3_flag",
    "post_llm_tier_3_1_flag",
    "post_llm_tier_3_2_flag",
    "post_llm_tier_3_3_flag",
    "post_llm_tier_3_4_flag",
    "post_llm_tier_4_1_flag",
    "post_llm_tier_4_2_flag",
    "post_llm_tier_4_3_flag",
    "post_llm_sub_tier_bucket",
    "in_tier1_post_llm_file",
    "in_tier2_post_llm_file",
    "in_tier3_post_llm_file",
    "in_tier4_post_llm_file",
    "in_hp1_hp4_post_llm_file",
    "shadow_demoted_core_candidate_rank_x",
    "shadow_replacement_core_candidate_rank_x",
    "shadow_demoted_core_candidate_rank_y",
    "shadow_replacement_core_candidate_rank_y",
)

_EXPLICIT_BOOLEAN_FIELDS = {
    "top15_selected",
    "top15_any_variant_selected",
    "shadow_selected",
    "shadow_any_variant_selected",
    "tier1_L1_llm_supported",
    "tier1_L2_causal_rerating",
    "tier1_L3_best_balanced",
    "tier1_L4_clean_high_priority",
    "tier1_L5_inflecting",
    "tier1_L6_mid_price_rerater",
    "tier1_L7_clean_non_distressed_rerater",
    "tier2_L1_llm_supported",
    "tier2_L2_causal_rerating",
    "tier2_L3_best_balanced",
    "tier3_L1_llm_supported",
    "tier3_L2_inflecting",
    "tier3_L3_persistent_positive",
    "tier3_L4_persistent_high_priority",
    "tier4_L1_llm_supported",
    "tier4_L2_causal_rerating",
    "tier4_L3_clean_high_priority",
    "hp0_high_price_broad",
    "hp1_quality_pullback",
    "hp2_dislocation_momentum_priority",
    "hp2_dislocation_momentum_watch",
    "hp3_large_quality_theme_exception",
    "hp4_score_reacceleration_watch",
    "hp_production_extension",
    "hp_research_extension",
    "hp1_LLM_best",
    "hp2_LLM_best",
    "hp2_watch_LLM_best",
    "hp3_theme_confirmed",
    "hp4_LLM_supported",
    "hp_LLM_best",
    "force_llm_extraction",
    "entry_score_is_provisional",
    "has_post_llm",
    "in_tier1_post_llm_file",
    "in_tier2_post_llm_file",
    "in_tier3_post_llm_file",
    "in_tier4_post_llm_file",
    "in_hp1_hp4_post_llm_file",
    "post_llm_demote_overrideable",
    "rm1_low_price_dislocation_momentum",
    "rm2_weak_acceleration",
    "rm3_mid_price_dislocation_momentum",
    "rm4_persistent_repricing_wave",
    "repricing_momentum_priority",
    "repricing_momentum_extension",
    "repricing_started",
    "repricing_confirmed",
    "theme_active",
    "theme_leader_or_direct_beneficiary",
    "theme_ai_data_center",
    "theme_ai_optical_networking",
    "theme_semiconductor_materials",
    "theme_compound_semiconductor",
    "theme_photonics",
    "theme_critical_materials",
    "theme_semicap_datacenter_confirmed",
    "force_pm_underwriting_flag",
    "is_partial_live_quarter",
    "eligible_for_backtest",
    "winner_90d_30pct",
    "loser_90d_minus30pct",
    "theme_acceleration_research_visibility",
    "theme_acceleration_rescan_flag",
    "extended_candidate_universe",
    "extended_research_universe",
}

FLAG_FIELDS = tuple(
    field
    for field in REQUIRED_COMPLETE_PANEL_COLUMNS
    if field.endswith("_flag") or field in _EXPLICIT_BOOLEAN_FIELDS
)

_MISSING_REASON_FIELDS = {
    "revenue_value": "revenue_value_missing_reason",
    "net_income_value": "net_income_value_missing_reason",
    "assets_value": "assets_value_missing_reason",
    "operating_cash_flow_value": "operating_cash_flow_value_missing_reason",
    "investing_cash_flow_value": "investing_cash_flow_value_missing_reason",
    "financing_cash_flow_value": "financing_cash_flow_value_missing_reason",
    "llm_status": "llm_status_missing_reason",
    "post_llm_candidate_flag": "post_llm_missing_reason",
    "top15_selected": "selection_missing_reason",
    "shadow_selected": "selection_missing_reason",
}


def missing_reason_field(field: str) -> str:
    """Return the canonical missing-reason sidecar for a value field."""

    return _MISSING_REASON_FIELDS.get(field, f"{field}_missing_reason")


def default_for_field(field: str) -> str:
    """Return the canonical blank-fill default for a complete-panel field."""

    if field in FLAG_FIELDS:
        return "0"
    return ""
