def get_large_cap_v1_sector_map() -> dict[str, str]:
    return {
        "AAPL": "Technology",
        "MSFT": "Technology",
        "AMZN": "Consumer Discretionary",
        "GOOGL": "Communication Services",
        "META": "Communication Services",
        "NVDA": "Technology",
        "AVGO": "Technology",
        "BRK.B": "Financials",
        "JPM": "Financials",
        "V": "Financials",
        "MA": "Financials",
        "WMT": "Consumer Staples",
        "COST": "Consumer Staples",
        "XOM": "Energy",
        "LLY": "Healthcare",
        "UNH": "Healthcare",
        "JNJ": "Healthcare",
        "PG": "Consumer Staples",
        "HD": "Consumer Discretionary",
        "CRM": "Technology",
        "ORCL": "Technology",
        "NFLX": "Communication Services",
        "ABBV": "Healthcare",
        "KO": "Consumer Staples",
        "PEP": "Consumer Staples",
    }
