"""Execution constants shared by paper/live broker helpers."""

SUCCESS_STATUSES = {"SUCCESS", "SUCCESS_CACHED"}
EXECUTION_MODE_PAPER = "paper"
EXECUTION_MODE_LIVE = "live"
EXECUTION_MODE_ALPACA_PAPER = "alpaca-paper"
EXECUTION_MODE_ALPACA_LIVE = "alpaca-live"
TERMINAL_BROKER_STATUSES = {"FILLED", "CANCELED", "REJECTED", "EXPIRED", "REPLACED"}
INTENT_CATEGORY_HEDGE = "HEDGE"
