from typing import Annotated, Sequence
from typing_extensions import TypedDict
from langgraph.graph import MessagesState


class AgentState(MessagesState):
    company_of_interest: Annotated[str, "Company that we are interested in trading"]
    trade_date: Annotated[str, "What date we are trading at"]

    sender: Annotated[str, "Agent that sent this message"]

    # research step
    market_report: Annotated[str, "Report from the Market Analyst"]
    news_report: Annotated[
        str, "Report from the News Researcher of current world affairs"
    ]
    fundamentals_report: Annotated[str, "Report from the Fundamentals Researcher"]

    investment_plan: Annotated[str, "Plan generated from analyst reports"]

    trader_investment_plan: Annotated[str, "Plan generated by the Trader"]

    final_trade_decision: Annotated[str, "Final trading decision"]
    pretrade_risk_brief: Annotated[
        str,
        "Pre-trade portfolio risk snapshot and hedge recommendation context",
    ]

    # Hedging / portfolio-risk context
    portfolio_snapshot: Annotated[dict, "Portfolio risk snapshot"]
    market_regime: Annotated[dict, "Market regime snapshot"]
    hedge_signal: Annotated[dict, "Computed hedge signal"]
    hedge_decision: Annotated[dict, "Computed hedge decision"]

    # Computed fundamental metrics from Python engine
    fundamental_metrics: Annotated[dict, "Computed fundamental metrics from Python engine"]

    # Computed macro regime metrics from Python engine
    macro_metrics: Annotated[dict, "Computed macro regime metrics from Python engine"]
    momentum_metrics: Annotated[dict, "Computed momentum metrics from Python engine"]

    # Deal flow signals from sourcing pipeline
    dealflow_context: Annotated[dict, "Deal flow signals from sourcing pipeline"]


    # Past trade outcomes from track record
    trade_lessons: Annotated[str, "Past trade outcomes from track record"]

    # Aeternus scoring
    aeternus_score: Annotated[dict, "Aeternus score, rating, and breakdown"]

    # Structured trader verdict with scenarios and invalidation conditions
    structured_trader_verdict: Annotated[dict, "Structured trader verdict with scenarios and invalidation conditions"]

    # Red Team Agent critique of dominant thesis
    red_team_critique: Annotated[dict, "Red Team Agent's critique of the dominant investment thesis with logical flaw analysis"]

    # Portfolio context for risk discussion
    portfolio_context: Annotated[str, "Portfolio composition, calibration feedback, drawdown state for risk discussion"]

    # Drawdown mode flag
    drawdown_mode: Annotated[bool, "Whether portfolio is in drawdown mode — shifts discussion question"]

    # Pre-fetched research data with quality metadata
    market_raw: Annotated[dict, "Pre-fetched market data with quality metadata"]
    news_raw: Annotated[dict, "Pre-fetched news data with quality metadata"]
    fundamentals_raw: Annotated[dict, "Pre-fetched fundamentals data with quality metadata"]
