from typing import Annotated, Sequence
from datetime import date, timedelta, datetime
from typing_extensions import TypedDict, Optional
from langchain_openai import ChatOpenAI
from tradingagents.agents import *
from langgraph.prebuilt import ToolNode
from langgraph.graph import END, StateGraph, START, MessagesState


def _merge_risk_state(a: dict, b: dict) -> dict:
    """Merge two RiskDebateState partial updates from parallel risk analysts.

    Each analyst writes only its own response field (the others are copied from
    the initial empty state). Prefer non-empty values so sequential LangGraph
    reducer calls don't clobber responses already written by other analysts.
    """
    merged = dict(a) if a else {}
    for k, v in (b or {}).items():
        if v or not merged.get(k):
            merged[k] = v
    return merged


# Researcher team state
class InvestDebateState(TypedDict):
    bull_history: Annotated[
        str, "Bullish Conversation history"
    ]  # Bullish Conversation history
    bear_history: Annotated[
        str, "Bearish Conversation history"
    ]  # Bullish Conversation history
    history: Annotated[str, "Conversation history"]  # Conversation history
    current_response: Annotated[str, "Latest response"]  # Last response
    judge_decision: Annotated[str, "Final judge decision"]  # Last response
    count: Annotated[int, "Length of the current conversation"]  # Conversation length


# Risk management team state
class RiskDebateState(TypedDict):
    risky_history: Annotated[
        str, "Risky Agent's Conversation history"
    ]  # Conversation history
    safe_history: Annotated[
        str, "Safe Agent's Conversation history"
    ]  # Conversation history
    neutral_history: Annotated[
        str, "Neutral Agent's Conversation history"
    ]  # Conversation history
    history: Annotated[str, "Conversation history"]  # Conversation history
    latest_speaker: Annotated[str, "Analyst that spoke last"]
    current_risky_response: Annotated[
        str, "Latest response by the risky analyst"
    ]  # Last response
    current_safe_response: Annotated[
        str, "Latest response by the safe analyst"
    ]  # Last response
    current_neutral_response: Annotated[
        str, "Latest response by the neutral analyst"
    ]  # Last response
    judge_decision: Annotated[str, "Judge's decision"]
    count: Annotated[int, "Length of the current conversation"]  # Conversation length


class AgentState(MessagesState):
    company_of_interest: Annotated[str, "Company that we are interested in trading"]
    trade_date: Annotated[str, "What date we are trading at"]

    sender: Annotated[str, "Agent that sent this message"]

    # research step
    market_report: Annotated[str, "Report from the Market Analyst"]
    news_report: Annotated[
        str, "Report from the News Researcher of current world affairs"
    ]
    fundamentals_report: Annotated[str, "Report from the Fundamentals Researcher"]

    # researcher team discussion step
    investment_debate_state: Annotated[
        InvestDebateState, "Current state of the debate on if to invest or not"
    ]
    investment_plan: Annotated[str, "Plan generated by the Analyst"]

    trader_investment_plan: Annotated[str, "Plan generated by the Trader"]

    # risk management team discussion step
    # Uses _merge_risk_state reducer so parallel risk analyst nodes can each write
    # their own response field without clobbering each other (Phase A fan-out).
    risk_debate_state: Annotated[RiskDebateState, _merge_risk_state]
    final_trade_decision: Annotated[str, "Final decision made by the Risk Analysts"]
    pretrade_risk_brief: Annotated[
        str,
        "Pre-trade portfolio risk snapshot and hedge recommendation context",
    ]

    # Hedging / portfolio-risk context
    portfolio_snapshot: Annotated[dict, "Portfolio risk snapshot"]
    market_regime: Annotated[dict, "Market regime snapshot"]
    hedge_signal: Annotated[dict, "Computed hedge signal"]
    hedge_decision: Annotated[dict, "Computed hedge decision"]

    # Computed fundamental metrics from Python engine
    fundamental_metrics: Annotated[dict, "Computed fundamental metrics from Python engine"]

    # Computed macro regime metrics from Python engine
    macro_metrics: Annotated[dict, "Computed macro regime metrics from Python engine"]
    momentum_metrics: Annotated[dict, "Computed momentum metrics from Python engine"]

    # Deal flow signals from sourcing pipeline
    dealflow_context: Annotated[dict, "Deal flow signals from sourcing pipeline"]

    # Structured verdict from Risk Judge (bypasses LLM signal extraction)
    structured_verdict: Annotated[dict, "Structured verdict from Risk Judge"]

    # Past trade outcomes from track record
    trade_lessons: Annotated[str, "Past trade outcomes from track record"]

    # Aeternus scoring
    aeternus_score: Annotated[dict, "Aeternus score, rating, and breakdown"]

    # Structured trader verdict with scenarios and invalidation conditions
    structured_trader_verdict: Annotated[dict, "Structured trader verdict with scenarios and invalidation conditions"]

    # Red Team Agent critique of dominant thesis
    red_team_critique: Annotated[dict, "Red Team Agent's critique of the dominant investment thesis with logical flaw analysis"]

    # Portfolio context for risk debate
    portfolio_context: Annotated[str, "Portfolio composition, calibration feedback, drawdown state for risk debate"]

    # Drawdown mode flag
    drawdown_mode: Annotated[bool, "Whether portfolio is in drawdown mode — shifts debate question"]

    # Pre-fetched research data with quality metadata
    market_raw: Annotated[dict, "Pre-fetched market data with quality metadata"]
    news_raw: Annotated[dict, "Pre-fetched news data with quality metadata"]
    fundamentals_raw: Annotated[dict, "Pre-fetched fundamentals data with quality metadata"]
